token: token             # Replace with a desired token
os:
  hostname: node1        # Set a hostname. This can be omitted if DHCP server offers hostnames.
  ssh_authorized_keys:
  - ssh-rsa ...          # Replace with your public key
  password: p@ssword     # Replace with a your password
install:
  mode: create
  mgmt_interface: eth0   # The management interface name
  device: /dev/sda       # The target disk to install
  iso_url: https://releases.rancher.com/harvester/master/harvester-amd64.iso
#  tty: ttyS1,115200n8   # For machines without a VGA console
