---
- name: create "Install Node {{ node_number}}" message
  shell: >
    figlet "Installing Node {{ node_number }}" 2>/dev/null || echo "Booting Node {{ node_number }}"
  register: figlet_result

- name: print "Booting Node {{ node_number }}"
  debug:
    msg: "{{ figlet_result.stdout }}"

- name: set Harvester Node IP fact
  set_fact:
    harvester_node_ip: "{{ harvester_network_config['cluster'][node_number | int]['ip'] }}"

- name: boot Harvester Node {{ node_number }}
  shell: >
    vagrant up harvester-node-{{ node_number }}
  register: harvester_node_boot_result
