
- name: install isc-dhcp-server
  apk:
    name: dhcp
    state: present
    update_cache: yes

- name: configure ipxe.conf
  copy:
    src: ipxe.conf
    dest: /etc/dhcp/
  notify: restart dhcp

- name: configure dhcpd.conf
  template:
    src: dhcpd.conf.j2
    dest: /etc/dhcp/dhcpd.conf
  notify: restart dhcp
