---
- name: install isc-dhcp-server
  apt:
    name: isc-dhcp-server
    state: present
    update_cache: yes
  when: settings['install_packages']

- name: configure isc-dhcp-server interface
  copy:
    src: isc-dhcp-server
    dest: /etc/default/
  notify: restart dhcp

- name: configure ipxe.conf
  copy:
    src: ipxe.conf
    dest: /etc/dhcp/
  notify: restart dhcp

- name: configure dhcpd.conf
  template:
    src: dhcpd.conf.j2
    dest: /etc/dhcp/dhcpd.conf
  notify: restart dhcp

- sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: true
    state: present
    reload: true

- name: masquerade VM traffics
  iptables:
    table: nat
    chain: POSTROUTING
    source: 192.168.0.0/24 # fix me
    jump: MASQUERADE
    out_interface: eth0
