---
- name: install tftpd-hpa
  package:
    name: "{{ tftpd_package_names[ansible_facts['os_family']] }}"
    state: present

- name: create tftp root
  file:
    path: /tftpboot
    state: directory

- name: configure tftp
  template:
    src: "{{ tftpd_conf_templates[ansible_facts['os_family']] }}"
    dest: "{{ tftpd_conf_dests[ansible_facts['os_family']] }}"
  notify: restart tftp
